title: 2025 Sustainable Futures Resource Fair
description: A resource fair focused on health and environmental sustainability
baseurl: "/sustainablefutures25"
url: "https://alxdolphin.github.io"
theme: jekyll-theme-minimal 